image: node:20

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules/

variables:
  PNPM_CACHE_FOLDER: .pnpm-store

before_script:
  - corepack enable
  - corepack prepare pnpm@9.15.4 --activate
  - pnpm config set store-dir $PNPM_CACHE_FOLDER

pages:
  stage: deploy
  script:
    - pnpm install
    - pnpm build
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"